### ISSUE TITLE
Fix back browser button functionality in member/site/group directories 

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#195] opened 2015-01-06 21:25 UTC
When user clicks the "back" button on the browser to return to a member/site/group directory after viewing an individual member/site/group, they are always returned to page 1 of results rather than the last page viewed.

**Comment by JonathanReeve** [comment] 2015-01-06 21:51
This looks like a duplicate of #182. This happens on vanilla CBOX, as well, judging from playing around with NYC-DH a little. It seems related to #176. Some AJAX filters are sticky (selecting the "My Groups" tab, for instance), while some, like pages, aren't. I'll have to look into which of these filters are getting stored in cookies, and why.

**Comment by JonathanReeve** [comment] 2015-01-06 21:52
Closing in favor of #182.

**Closed by JonathanReeve** 2015-01-06 21:52 UTC
Labels: bug, duplicate
