### ISSUE TITLE
changing the visibility of a group doesn't change the visibility of a forum

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#265] opened 2015-05-06 13:36 UTC
Hey @JonathanReeve, 

I started 2 topics yesterday to my hidden group, "Katherine's Public Group." 

![katherine s public group - discussion - mla commons clipular 1](https://cloud.githubusercontent.com/assets/8835589/7494008/2f8a012e-f3d3-11e4-87b9-052593d31de0.png)

This is what the activity stream looks like when I log out: 

![site-wide activity - mla commons clipular 3](https://cloud.githubusercontent.com/assets/8835589/7494015/378ae5f0-f3d3-11e4-8b71-208ec673d92c.png)

**Comment by JonathanReeve** [comment] 2015-05-06 13:55
I can't reproduce this. Here's what I tried: 

First Test. 
 1. Added test user `commonstest` to a committee (private group)
 2. Posted a new forum post in "discussion" area.
 3. It didn't appear in the activity stream. 

Second Test. 
 1. Using test user `commonstest`, posted a forum thread in hidden group `MLA Commons Dev Team`. 
 2. Verified that this post doesn't appear in the activity stream. 

Could you try to post in other hidden and private groups (on Dickenson), and see if you still see things in the activity stream?

**Comment by JonathanReeve** [comment] 2015-05-06 13:55
Judging from the name of this group, I'm guessing that it was once a public group, but now it's hidden? Maybe that has something to do with it.

**Comment by JonathanReeve** [comment] 2015-05-06 14:33
Duplicate of #189.

**Closed by JonathanReeve** 2015-05-06 14:33 UTC
Labels: bug, duplicate
