### ISSUE TITLE
numeric indicator for "Docs" in group sidebar

### ISSUE THREAD

**Issue by kfitz** [mlaa/cbox-mla#223] opened 2015-02-06 18:53 UTC
Would it be possible for us to add a numeric indicator to the "Docs" button (as exists for "Files" and "Members"), so that it's possible to know at a glance if a group you're in has any Docs you should perhaps look at?

**Comment by terrainsvagues** [comment] 2015-02-06 18:58
@kfitz, @JonathanReeve and I were just discussing this today. See https://github.com/mlaa/buddypress-docs/issues/1.

**Comment by kfitz** [comment] 2015-02-06 19:01
Ha, great minds, etc. @JonathanReeve, feel free to remove this issue or merge it with the other one or whatever works best!

**Comment by JonathanReeve** [comment] 2015-02-06 19:02
Yep, this is a duplicate of mlaa/buddypress-docs#1. There's an open issue about this upstream, too--apparently this featured used to exist, but was removed due to some technical difficulties. See https://github.com/boonebgorges/buddypress-docs/issues/423.

**Closed** 2015-02-06 19:03 UTC
Labels: duplicate
