### ISSUE TITLE
Viewing "My Contacts" from /activity shows activity for all users, not just my contacts

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#266] opened 2015-05-06 15:41 UTC
Go to https://commons.mla.org/activity/ and click "My Contacts." The activity stream does not change to reflect your contacts.

**Comment by JonathanReeve** [comment] 2015-05-06 15:51
So @rekmla says this is mlaa/humcore#4. It looks like humcore handling of activities is causing this and other activity-related issues. Closing this as a duplicate of that one.

**Closed by JonathanReeve** 2015-05-06 15:51 UTC
Labels: bug, priority
